import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import AboutOmaxe from "../../components/AboutOmaxe";
import Property from "../../components/Property";
import OurTeam from "../../components/OurTeam";
import Testimonial from "../../components/Testimonial";
import Footer from "../../components/Footer/Footer";
import ContactUs from "../../components/Contact Us";
import Navigation from "../../components/Navigation";
import TopComponent from "../../components/TopComponent";
import Project from "../../components/Project";
import ProjectMobileView from "../../components/Project/MobileView";
import TestimonialMobileView from "../../components/Testimonial/MobileView";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const scrollToSection = (id) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Navigation />
        <TopComponent />
        <AboutOmaxe />
        <Project />
        <ProjectMobileView />
        {/* <Property typeOfProperty='Live' /> */}
        {/* <Property typeOfProperty='Past' /> */}
        <OurTeam />
        <Testimonial />
        <TestimonialMobileView />
        <ContactUs />
        <Footer scrollToSection={scrollToSection} />
      </main>
    </>
  );
}
